import { User, Match, Message } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    ageRange: '25-34',
    location: 'San Francisco, CA',
    role: 'Co-Founder',
    startupStage: 'MVP',
    skills: ['Product Management', 'UI/UX Design', 'Growth Hacking'],
    industries: ['AI/Machine Learning', 'SaaS'],
    goals: 'Building an AI-powered productivity tool. Looking for a technical co-founder to scale our MVP.',
    lookingFor: ['Technical Co-Founder', 'Developer'],
    bio: 'Former PM at Google. Passionate about using AI to enhance human productivity. Built 2 profitable side projects. Stanford CS grad.',
    linkedIn: 'linkedin.com/in/sarahchen',
    verified: true,
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    lastActive: new Date(),
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    ageRange: '35-44',
    location: 'Austin, TX',
    role: 'Mentor',
    startupStage: 'Scaling',
    skills: ['Fundraising', 'Business Development', 'Sales'],
    industries: ['SaaS', 'B2B Tools'],
    goals: 'Exited my SaaS company last year. Now mentoring early-stage founders on fundraising and growth.',
    lookingFor: ['Mentees', 'Collaborators'],
    bio: 'Built and sold 2 B2B SaaS companies. Raised $15M+ in VC funding. Happy to share lessons learned with ambitious founders.',
    linkedIn: 'linkedin.com/in/marcusjohnson',
    verified: true,
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    lastActive: new Date(Date.now() - 3600000),
  },
  {
    id: '3',
    name: 'Priya Patel',
    email: 'priya@example.com',
    ageRange: '25-34',
    location: 'New York, NY',
    role: 'Developer',
    startupStage: 'Idea',
    skills: ['Full-Stack Development', 'Mobile Development', 'DevOps'],
    industries: ['FinTech', 'Blockchain/Web3'],
    goals: 'Exploring Web3 and decentralized finance. Open to co-founding or joining as early engineer.',
    lookingFor: ['Co-Founder', 'Team Members'],
    bio: 'Senior engineer at Stripe. 8 years of experience building scalable systems. Looking to leverage blockchain for financial inclusion.',
    github: 'github.com/priyapatel',
    portfolio: 'priya.dev',
    verified: true,
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
    lastActive: new Date(Date.now() - 7200000),
  },
  {
    id: '4',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    ageRange: '25-34',
    location: 'Miami, FL',
    role: 'Designer',
    startupStage: 'Launched',
    skills: ['UI/UX Design', 'Product Management', 'Branding'],
    industries: ['Consumer Apps', 'Social Media'],
    goals: 'Building a community-focused social app. Need help with marketing and user acquisition.',
    lookingFor: ['Marketer', 'Growth Hacker'],
    bio: 'Award-winning product designer. Led design at 2 unicorn startups. Obsessed with creating delightful user experiences.',
    portfolio: 'alexrivera.design',
    linkedIn: 'linkedin.com/in/alexrivera',
    verified: true,
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    lastActive: new Date(Date.now() - 1800000),
  },
  {
    id: '5',
    name: 'Emily Zhang',
    email: 'emily@example.com',
    ageRange: '18-24',
    location: 'Boston, MA',
    role: 'Co-Founder',
    startupStage: 'Idea',
    skills: ['Content Creation', 'Social Media', 'Marketing'],
    industries: ['EdTech', 'Consumer Apps'],
    goals: 'Creating a platform to make learning more engaging for Gen Z. Looking for a technical co-founder.',
    lookingFor: ['Technical Co-Founder', 'Developer', 'Designer'],
    bio: 'MIT sophomore studying CS + Business. Grew Instagram to 100K followers. Passionate about education innovation.',
    linkedIn: 'linkedin.com/in/emilyzhang',
    verified: false,
    photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop',
    lastActive: new Date(),
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david@example.com',
    ageRange: '35-44',
    location: 'Seattle, WA',
    role: 'Investor',
    startupStage: 'Scaling',
    skills: ['Fundraising', 'Business Development', 'Strategy'],
    industries: ['AI/Machine Learning', 'HealthTech'],
    goals: 'Angel investor focused on AI and healthcare startups. Invested in 15+ companies.',
    lookingFor: ['Investment Opportunities', 'Advisee'],
    bio: 'Former VP at Amazon. Now angel investor and startup advisor. Particularly interested in AI applications in healthcare.',
    linkedIn: 'linkedin.com/in/davidkim',
    verified: true,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    lastActive: new Date(Date.now() - 5400000),
  },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'm1',
    userId: 'current',
    user: MOCK_USERS[1],
    matchedAt: new Date(Date.now() - 86400000),
    lastMessage: {
      id: 'msg1',
      matchId: 'm1',
      senderId: '2',
      content: "I'd love to share some fundraising tips. When are you free for a call?",
      timestamp: new Date(Date.now() - 3600000),
      read: false,
    },
    unreadCount: 2,
  },
  {
    id: 'm2',
    userId: 'current',
    user: MOCK_USERS[2],
    matchedAt: new Date(Date.now() - 172800000),
    lastMessage: {
      id: 'msg2',
      matchId: 'm2',
      senderId: 'current',
      content: 'Your Web3 experience sounds amazing! Would love to discuss potential collaboration.',
      timestamp: new Date(Date.now() - 7200000),
      read: true,
    },
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg1-1',
    matchId: 'm1',
    senderId: '2',
    content: 'Hey! Saw you\'re working on an AI productivity tool. That\'s exciting!',
    timestamp: new Date(Date.now() - 86400000),
    read: true,
  },
  {
    id: 'msg1-2',
    matchId: 'm1',
    senderId: 'current',
    content: 'Thanks Marcus! Yes, we just finished our MVP. Your fundraising experience would be invaluable.',
    timestamp: new Date(Date.now() - 82800000),
    read: true,
  },
  {
    id: 'msg1-3',
    matchId: 'm1',
    senderId: '2',
    content: "I'd love to share some fundraising tips. When are you free for a call?",
    timestamp: new Date(Date.now() - 3600000),
    read: false,
  },
];
